Traceback (most recent call last):
  File "train.py", line 23, in <module>
    dataset = ExampleDataset()
  File "train.py", line 11, in __init__
    self.x = torch.from_numpy(xy[:, 1:])
  File "/home/eegroup/eemsrl03/miniconda3/envs/env1/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/eegroup/eemsrl03/miniconda3/envs/env1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), slice(1, None, None))' is an invalid key
